[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
casting_votes_onchain = "7vnKReNaiPPFLVtFKWp2qip77TFct3ZqJbbsdpXm8Pji"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/harshghodkar/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
